---
title: "<b>Israel Cognitive Psychology List (ISCoP) Newsletter November 2021</b>"
---

<style>
h1 {
    position: relative;
    font-size: 30px;
    z-index: 1;
    overflow: hidden;
    text-align: center;
    font-family: Times New Roman;
}
h1:before, h1:after {
    position: absolute;
    top: 51%;
    overflow: hidden;
    width: 100%;
    height: 1px;
    content: '\a0';
    background-color: darkred;
}
h1:before {
    margin-left: -50%;
    text-align: right;
}

h4 {
    text-align: center;
    font-size: 20px;
    font-family: Times New Roman;
}

hr {
    height: 1px;
    background-color: darkred;
    text-align: center;
}
</style>


<style>
.rtl {direction:rtl;
      font-family: Times New Roman;
      font-size: 18px;}
.eng {direction:ltr;
      font-family: Times New Roman;
      font-size: 18px;}
.abstract {text-align: center;}
.details {text-align: left;}
</style>

<div class="rtl">
<hr>
#### <b>תוכן</b>
<hr>
1. דברי פתיחה
2. כנסים קרובים בישראל
3. כנסים קרובים בחו"ל
4. הצעות למלגות, משרות תקן, פוסט-דוקטורט ודוקטורט
5. קול קורא להגשת מאמרים לגיליונות מיוחדים בתחומי הקוגניציה
\
\

<hr>
#### <b>דברי פתיחה</b>
<hr>
 
אנו שמחים לשלוח את דף מידע לחודש נובמבר 2021 לרשימת התפוצה של פסיכולוגים\\ות קוגניטיביים, נוירופסיכולוגים\\ות, ומדענים\\ות קוגניטיביים בישראל. כידוע, בעקבות המצב, כנסים רבים מתבטלים ומשתנים כל הזמן. חשוב לוודא ולברר בעצמכם\\ן את הפרטים הספציפיים לגבי כל הודעה המופיעה בדף המידע ולעקוב אחר השינויים אצל המארגנים והמפרסמים עצמם. שימו לב: למרות שבחרנו לשמור על החלוקה של 'כנסים בארץ' ו-'כנסים בחו"ל', בפועל חלק מהכנסים הפכו למעשה לכנסים וירטואליים (online). 
אנו מודים לכל החברים אשר עוזרים בהפצתה של רשימת התפוצה שלנו ולכל החברים\\ות אשר מעבירים לנו מידע רלוונטי לפרסום בדף זה. אנו מבקשים להזכיר: על מנת שלא להעמיס על תיבות המייל של החברים ברשימה אנו מוציאים את דף המידע אחת לחודש (באמצע כל חודש) ונמנעים מלפרסם דברים נוספים בין דפי המידע. אי-לכך אנו מבקשים לשלוח לנו מידע זמן מה מראש על מנת שהוא יהיה רלוונטי גם בעת פרסום דף המידע הבא. כל המעוניין להפיץ מידע רלוונטי בעזרת דפי המידע הללו ו\\או להציע הצעות ורעיונות לשיפור והתפתחות יכול ליצור קשר עם אביב אביטן aviviscop@gmail.com. על מנת להסיר או להוסיף שם מרשימת התפוצה אנא שלחו דואר לדזירה מלול desiree@bgu.ac.il .

</div>

\
\
<div class="eng">
**Please let us know…** \
We would like to offer our readership the opportunity to become involved by contributing memorandums and awards of interest to the newsletter. If you would like to let us know of an important award a member of the community received or if you would like to contribute a memorandum on past members of our community, please send an email to aviviscop@gmail.com and we will gladly consider adding the information to the newsletter.
</div>

\
\
<hr>
#### <b>כנסים קרובים בישראל</b>
<hr>
<div class="rtl">
<b>כנס השנתי של החטיבה השיקומית: "קרוב אל עצמך"</b>
\
<b>23-25 בנובמבר, 2021</b>
\
<b>מלון ניר עציון</b>
\
אנו שמחים ונרגשים להכריז על הכנס השנתי של החטיבה השיקומית בהפ"י לשנת 2021.
השנה האחרונה הייתה אחת המורכבות שידענו, הן כפרטים והן כחברה, הן במעגלים האישיים והן במעגלים המקצועיים. שנה שבה נגיף אחד חייב אותנו לבחון מחדש חלק מן הנחות היסוד שלנו לגבי טיפול ואבחון, והצריך מאיתנו גמישות ויצירתיות כדי להמשיך ולהתאים את עצמנו למציאות המשת נה, לדרישות המערכות שבהן אנו עובדים ולצרכי המטופלות והמטופלים.
והנה, בחלוף השנה הזו, אנו מזמינים אתכן ואתכם לכנס, שבו על הצרכים שלכם אנחנו מבקשים לענות. כנס ששם אותנו, הפסיכולוגיות והפסיכולוגים, במרכז, וקורא לנו להיות הכי קרוב אל עצמנו.
אחרי תקופה של ריחוק חברתי, סגרים ובידודים, אנו מזמינים אתכם לחגוג את ה"ביחד". והשנה לראשונה, אנו מארגנים כנס של 3 ימים שייערך במתכונת של סדנאות עומק. זוהי הזדמנות עבור כולנו להיפגש עם חברים וחברות, עמיתים ועמיתות, ליצור שיתופי פעולה חדשים ולהמשיך להתפתח כפרופסיה וכנשות ואנשי מקצוע.
\
הרכב הכנס:
\
א. הרצאות מפתח.
\
ב. סדנאות תלת-יומיות בקבוצות קטנות.
\
ג. תערוכת פוסטרים במסגרתה פרס יינתן לפוסטר עם העבודה המצטיינת.
\
ד. הענקת פרסי חדשנות בעשייה בתחום השיקומי ופרס מפעל חיים.
\
ה. פעילויות תרבות, בילוי ומפגשים חברתיים בלתי פורמאליים.
\
<div class='abstract'>
[פרטים נוספים](https://cdn-media.web-view.net/i/wjwc8c/_________-_____2021_1.pdfp)
</div>
\
\
<b>הכינוס השנתי ה-18 של האגודה הישראלית לפסיכומטריקה (אפי)</b>
\
<b>17 לינואר, 2022</b>
\
<b>מלון יערים, מעלה החמישה</b>
\
הכינוס השנתי של אפי הוא פורום ייחודי לחילופי רעיונות, להצגת תוצאות של מחקרים ולדיון במגוון נושאים ויישומים בתחום הפסיכומטריקה. תכנית הכינוס תכלול הצגה של ההצעות שתתקבלנה.
על ההצעות להיות בנושאי מדידה פסיכולוגית וחינוכית (פסיכומטריקה) ומעולמות תוכן כמו חינוך, ארגון, מיון, רפואה, השכלה גבוהה ותעסוקה. הצעות רלוונטיות הן אלה העוסקות בפסיכומטריקה עצמה או ביישום שלה בתחומים אחרים כמו מחקרי
אפקטיביות והערכת תוכניות ומדיניות.  
\
<div class="abstract">
<b>Abstract submission is now closed</b>
\
\
[פרטים נוספים](https://7c53a3f5-e54d-40e1-a4e5-4899172c44fc.filesusr.com/ugd/295104_6778712abcbd430590b3acf7e15b85fe.pdf)
</div>







